import Footer from "@/components/Footer";
import ToastProvider from "@/components/ToastProvider";
import { Moulpali, Roboto } from "next/font/google";
import "./globals.css";
// turjo vai recomendend for Moulpali fonts

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const moulpali = Moulpali({
  variable: "--font-moulpali",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Fa Business",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-moulpali antialiased`}>
        <ToastProvider>{children}</ToastProvider>
        <Footer />
      </body>
    </html>
  );
}
